# Generated by Django 4.1.7 on 2023-05-17 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_alter_data_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="data",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="data",
                to="authentication.user",
            ),
        ),
    ]
