# Generated by Django 4.1.7 on 2023-06-14 07:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0008_personal"),
    ]

    operations = [
        migrations.AddField(
            model_name="personal",
            name="sex",
            field=models.TextField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="personal",
            name="citizenship",
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="personal",
            name="nationality",
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
