# Generated by Django 4.1.7 on 2023-06-14 07:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0009_personal_sex_alter_personal_citizenship_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personal",
            name="birthdate",
            field=models.DateTimeField(null=True),
        ),
    ]
