# Generated by Django 4.1.7 on 2023-06-14 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0010_alter_personal_birthdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personal",
            name="citizenship",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="personal",
            name="nationality",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="personal",
            name="sex",
            field=models.CharField(
                choices=[
                    ("Männlich", "männlich"),
                    ("Weiblich", "weiblich"),
                    ("Divers", "divers"),
                ],
                max_length=50,
            ),
        ),
    ]
