# Generated by Django 4.1.7 on 2023-06-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0013_alter_address_canton_alter_address_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="postalcode",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
