# Generated by Django 4.1.7 on 2023-06-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0014_alter_address_postalcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="registration_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
