# Generated by Django 4.1.7 on 2023-06-14 16:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0015_user_registration_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="registration_date",
        ),
    ]
