# Generated by Django 4.1.7 on 2023-06-19 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0019_health"),
    ]

    operations = [
        migrations.AddField(
            model_name="health",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="health",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
