# Generated by Django 4.1.7 on 2023-06-19 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0020_health_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="health",
            name="others",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="health",
            name="vaccines",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name="Criminal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crime", models.CharField(blank=True, max_length=50, null=True)),
                ("judgements", models.TextField(blank=True, max_length=200, null=True)),
                ("date", models.DateTimeField()),
                ("responsible", models.CharField(blank=True, max_length=50, null=True)),
                ("institution", models.CharField(blank=True, max_length=50, null=True)),
                ("nice2know", models.TextField(blank=True, max_length=200, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="criminals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
