# Generated by Django 4.1.7 on 2023-06-20 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0022_salary"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="salary",
            options={"ordering": ["-date"]},
        ),
        migrations.CreateModel(
            name="Absence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Urlaub", "urlaub"),
                            ("Krankheit", "krankheit"),
                            ("Sonstiges", "sonstiges"),
                        ],
                        max_length=50,
                    ),
                ),
                ("start", models.DateField()),
                ("end", models.DateField()),
                ("confirmation", models.BooleanField(default=False)),
                (
                    "beneficiary",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_absences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="absences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
