# Generated by Django 4.1.7 on 2023-06-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0023_alter_salary_options_absence"),
    ]

    operations = [
        migrations.AddField(
            model_name="absence",
            name="description",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
