# Generated by Django 4.1.7 on 2023-06-21 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0025_absence_creator_alter_absence_beneficiary"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="absence",
            options={"ordering": ["-start"]},
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("appearance", models.TextField(max_length=200)),
                ("teamwork", models.TextField(max_length=200)),
                ("helpfulness", models.TextField(max_length=200)),
                ("politeness", models.TextField(max_length=200)),
                ("communication", models.TextField(max_length=200)),
                ("work_quality", models.TextField(max_length=200)),
                ("work_organisation", models.TextField(max_length=200)),
                ("knowledge", models.TextField(max_length=200)),
                ("goals", models.TextField(max_length=200)),
                ("grade", models.FloatField()),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedbacks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
