# Generated by Django 4.1.7 on 2023-06-21 08:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0026_alter_absence_options_feedback"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feedback",
            options={"ordering": ["-date"]},
        ),
    ]
