# Generated by Django 4.1.7 on 2023-06-21 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0027_alter_feedback_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="evaluator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="evaluated_feedbacks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
