# Generated by Django 4.1.7 on 2023-06-26 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0029_reprimant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="health",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="health",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
