# Generated by Django 4.1.7 on 2023-07-28 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/uploads/about'),
        ),
    ]
