# Generated by Django 3.2.20 on 2023-11-25 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=200)),
                ('priority', models.CharField(choices=[('Niedrig', 'Niedrig'), ('Mittel', 'Mittel'), ('Hoch', 'Hoch'), ('Sonderfall', 'Sonderfall')], default='Niedrig', max_length=20)),
                ('status', models.CharField(choices=[('Todo', 'Todo'), ('In Bearbeitung', 'In Bearbeitung'), ('Fertig', 'Fertig')], default='Todo', max_length=20)),
                ('assigned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
