# Generated by Django 4.1.7 on 2023-05-22 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("Offen", "Offen"),
                    ("Angenommen", "Angenommen"),
                    ("Abgelehnt", "Abgelehnt"),
                    ("Abholbereit", "Abholbereit"),
                    ("Abgeschlossen", "Abgeschlossen"),
                ],
                default="Offen",
                max_length=50,
            ),
        ),
    ]
