# Generated by Django 4.1.7 on 2023-05-22 11:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_alter_reservation_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="author",
        ),
    ]
