# Generated by Django 4.1.7 on 2023-06-11 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_article_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-id', 'title']},
        ),
    ]
