# Generated by Django 4.1.7 on 2023-07-24 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_reservation_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-start_date']},
        ),
    ]
